### PR TITLE
remove client mode

### PR DESCRIPTION
**Pull request by debris**
This is quite opinionated pr as it removes one of the parity features. Since 2016 parity allows users to set an operation mode of the node, that is: `online`, `passive`, `dark` or `off`. I believe that our users (who are mostly power users), never use any other option that `online`. Therefore I believe it is feasible to remove this feature, especially that it's implementation is not very clear, nor idiomatic

### CODE REVIEW

**Comment by ordian** [comment]
should it be removed from `parity/cli/mod.rs` as well?

**Comment by dvdplm** [comment]
I know I've used `mode=offline` in the last few months but I can't remember why I did it (it's in my shell history). Do you know why it was added in the first place? One thing that is really odd about it is that it's "sticky": setting it persists across restarts. Is that what you mean by it being not idiomatic?
@joshua-mir do you know of anyone ever using this?

**Comment by joshua-mir** [comment]
I kinda disagree with this change - I do know of significant categories of users who use `passive` and `offline` - it seems used pretty regularly for people doing IOT stuff, embedded, and resource-limited environments, especially in combination with `--light`.

`passive` is really popular with people running "temporary" rpc endpoints as well.

**Comment by debris** [comment]
>  Is that what you mean by it being not idiomatic?

No. I'm referring to how this feature is implemented. `enum Mode` as it is implemented right now is used in a similar way to C enums and it doesn't prevent anyone from actually using `Client` incorrectly. And since there are no tests for this code, we can't even be sure if it's working accordingly to the intensions of the author.

> do you know of anyone ever using this?

When I think of this a bit more, `offline` might be used by someone who wants to run a single node chain for test purposes... but I can't think of any case when someone would like to change run mode in the runtime via rpc.

**Comment by debris** [comment]
> I kinda disagree with this change - I do know of significant categories of users who use passive and dark - it seems used pretty regularly for people doing IOT stuff, embedded, and resource-limited environments, especially in combination with --light.

I believe that mode is not even implemented for light clients 😞 

https://github.com/paritytech/parity-ethereum/blob/93fbbb9aaf161f21471050a2a3257f820c029a73/rpc/src/v1/impls/light/parity_set.rs#L124-L126

> `offline` is somewhat popular with people running "temporary" rpc endpoints as well.

what do you mean by saying temporary rpc endpoints?

**Comment by joshua-mir** [comment]
> what do you mean by saying temporary rpc endpoints?

Clone the db, spin up a node in `offline` mode, make your rpc requests, and then shut everything down.

**Comment by dvdplm** [comment]
> spin up a node in `offline` mode, make your rpc requests,

Ah, that's what I did too: spun up a silent node while benchmarking RPCs.

Ok, @debris, sounds like we're not removing this then. We should definitely clean up the code though, you up for that? Here or in a separate PR?

**Comment by debris** [comment]
A separate pr is better

**Pull request closed without merging**
