### PR TITLE
Remove support for hardware wallets

### PR DESCRIPTION
**Pull request by dvdplm**
Fixes https://github.com/paritytech/parity-ethereum/issues/10677

### CODE REVIEW

**Comment by dvdplm** [comment]
> cleanup the `README` after this and remove some dependencies that are not needed anymore

The README looks fine (i.e. no mention of hardware wallets) and I went looking for `libusb` and `hidapi` but found no mention of them. Do you know where I should look?

**Comment by niklasad1** [comment]
> The README looks fine (i.e. no mention of hardware wallets) and I went looking for libusb and hidapi but found no mention of them. Do you know where I should look?

My bad, it is only `libudev-dev` that is not needed anymore and I think the `Docker` files can be cleaned up (such as Android) but probably better to keep those out of this PR and create issues?

**Comment by dvdplm** [comment]
> but probably better to keep those out of this PR and create issues?

I went ahead and removed them to the best of my knowledge, but if you think it's a bad idea I can [revert the commit](https://github.com/paritytech/parity-ethereum/pull/10678/commits/3e5c52c00cf25d35fb4a49356a6cfe3dbc262650).

**Comment by niklasad1** [comment]
> I went ahead and removed them to the best of my knowledge, but if you think it's a bad idea I can revert the commit.

Cool, it looks good

**Pull request merged**
