### PR TITLE
Prevent blockchain & miner racing when accessing pending block.

### PR DESCRIPTION
**Pull request by tomusdrw**
The issue is that `client` might have imported a new block already, but `on_chain_new_blocks` notification has not been run yet (so new pending block was not yet constructed). This is even more visible now, when pending block construction may take significant amount of time (hundreds millis).
So the miner has a pending block with the same number as the best_block returned from `client`.

We could either:
1. Return a bit stale data (implemented in this PR)
2. Force miner to create a new pending block (I would avoid that, we don't really want to create pending blocks from RPC threads, since it's quite heavy)
3. Wait for the new pending block (if we know we run with `--force-sealing` or sth). This would required to have some kind of lock on the pending data. (I would also avoid that to prevent locking down the RPC cpupool).

Since the inherent nature of `pending` is that it's ephemeral (and the data might actually be invalid by the time you receive a response) I believe that returning stale data is the least evil approach.

Should address #9288

### CODE REVIEW

**Comment by tomusdrw** [comment]
I've noticed another possible issue that causes incorrect behaviour and will attempt to fix it now.

**Comment by tomusdrw** [comment]
Logs in #9288 indicated on another reason why it may be failing.
During reseal the pending block was actually `popped` of the queue, so it was no longer available. Added a fix for this, changing the semantics of `using_queue` a bit:
1. `pop_if` is replaced with `get_pending_if` (we always clone)
2. `push` was renamed to `set_pending`

So now we can push to an old block, but it's previous pending version is still available for the queries.

**Comment by tomusdrw** [comment]
@dvdplm yup, I mean exactly this, where we already imported a block with number `N` to the blockchain, but we have a pending block `N` that might be a little bit different though (but it's the same block that has been returned for all previous queries).

**Comment by debris** [comment]
does it need to backported?

**Pull request merged**
