### PR TITLE
Properly handle check_epoch_end_signal errors

### PR DESCRIPTION
**Pull request by sorpaas**
The function `check_epoch_end_signal` can fail, but currently its errors are silently ignored. This can cause other parts of engine to panic, and gets us issues like #9978. This PR moves `check_epoch_end_signal` out of `commit_block` so that its errors are properly handled.

When on error, the block is rejected. Nearly all times this is users' specification issue. With rejection, no further blocks will proceed thus allowing the user to rescue the chain without the need to kill the db.

### CODE REVIEW

**Comment by 5chdn** [comment]
Conflict in client, and needs a 2nd review :+1:

**Comment by ordian** [comment]
@sorpaas please resolve conflicts

**Comment by 5chdn** [comment]
Does not compile

**Comment by sorpaas** [comment]
Sorry I missed this!

**Pull request merged**
