### PR TITLE
fix(osx and windows builds): bump parity-daemonize

### PR DESCRIPTION
**Pull request by niklasad1**
Attempt to fix `Windows` and `OSX` builds

/cc @5chdn @ddorgan can you help me run this on Windows and OSX? Thanks

### CODE REVIEW

**Comment by HCastano** [comment]
Looks like it's building fine on my Mac now.

**Comment by niklasad1** [comment]
It fails because of the CI is running `rust 1.31.1`, see https://github.com/rust-lang/rust/issues/53130. Thus, it is fixed in `rust 1.32`

If we can bump to `rust 1.32` it would be find or any objections that we should support earlier rust versions?

**Comment by 5chdn** [comment]
why is CI using outdated rust versions @fevo1971 ?

**Comment by fevo1971** [comment]
> why is CI using outdated rust versions @fevo1971 ?

on mac & windows rust is updated daylay (at ~23:00h), for the docker image parity/rust:gitlab-ci used for all other builds this is not the case (embarrassingly for some quite some time). i coordinated with @TriplEight to finish his work on the new docker image  (based on the *rust:stable* image).

**Comment by niklasad1** [comment]
FYI, I've built `android` successfully locally, [log here](https://gist.githubusercontent.com/niklasad1/6e008b919ccb7864a107b49bfbc7381d/raw/cdc51ebe290bc3dadc130e5f15bfc3334525e428/build.log)

Thus, the `android pipeline` runs also an old version of Rust

**Pull request merged**
