### PR TITLE
Explicitly enable or disable Stratum in config file (Issue 9785)

### PR DESCRIPTION
**Pull request by lamafab**
Hi

This PR adds the requested feature from issue #9785.

**Changes**
- Users can now directly enable or disable Stratum in the configuration file:
```
[stratum]
disable = false
port = 8007
secret = "Yellow"
```
```
[stratum]
disable = true
```
- For backward compatibility reasons, Stratum is enabled by default **if** the `[stratum]` section is present and **not** disabled by setting `disable = true`.
- Contains additional tests for the Stratum section in the config file.

I've run those changes directly on my machine; it works as intended (assuming these are the expected requirements. IMO, it would be cleaner if Stratum was only enabled if we explicitly set a `enabled = true` option. This would break backward compatibility, however).

Any feedback is welcome.

### CODE REVIEW

**Comment by lamafab** [comment]
Are the CPP errors in your CI related to my changes? It does look like another problem, unless I'm wrong.

```
Scanning dependencies of target libparity
[ 10%] Creating directories for 'libparity'
[ 20%] No download step for 'libparity'
[ 30%] No update step for 'libparity'
[ 40%] No patch step for 'libparity'
[ 50%] No configure step for 'libparity'
[ 60%] Performing build step for 'libparity'
CMake Error at /builds/parity/parity-ethereum/parity-clib/examples/cpp/build/libparity-prefix/src/libparity-stamp/libparity-build-.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/builds/parity/parity-ethereum/parity-clib/examples/cpp/build/libparity-prefix/src/libparity-stamp/libparity-build--impl.cmake'

  See also

    /builds/parity/parity-ethereum/parity-clib/examples/cpp/build/libparity-prefix/src/libparity-stamp/libparity-build-*.log


CMakeFiles/libparity.dir/build.make:110: recipe for target 'libparity-prefix/src/libparity-stamp/libparity-build' failed
make[2]: *** [libparity-prefix/src/libparity-stamp/libparity-build] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libparity.dir/all' failed
make[1]: *** [CMakeFiles/libparity.dir/all] Error 2
make: *** [all] Error 2
Makefile:83: recipe for target 'all' failed
```

**Comment by niklasad1** [comment]
/cc @TriplEight any idea what's going on here?

I think we should enable `VERBOSE` build for the `cpp example` (I have no clue what's is going on)

```make VERBOSE=1 -j $THREADS```

**Comment by TriplEight** [comment]
@niklasad1 here you go: https://github.com/paritytech/parity-ethereum/pull/10524

**Comment by soc1c** [comment]
I just restarted the job and it worked, maybe hold back with hacking the pipelines and try restarting it in future? ;)

**Comment by HCastano** [comment]
We should also update the [wiki](https://wiki.parity.io/Configuring-Parity-Ethereum) to reflect this change. @lamafab  do you mind putting in a PR here: https://github.com/paritytech/wiki?

**Comment by lamafab** [comment]
@HCastano Sure, no problem. I will do that after work (this evening).

**Comment by stone212** [comment]
@lamafab You said `Stratum is enabled by default if the [stratum] section is present and not disabled by setting disable = true`

Does this mean:

Stratum is 

1. enabled by default if the [stratum] section is present
2. **not** disabled by setting `disable = true`

Why would you have `disable = true` if it does not disable it?

**Comment by lamafab** [comment]
@stone212 This decision was made for backwards compatibility reasons. Stratum is enabled if the `[stratum]` section is present, either with or without `disable = false`. If you set `disable = true`, then Stratum gets disabled.

Sorry for the confusion...

**Comment by stone212** [comment]
@lamafab It's a good decision, I just wanted to make the language clear.  Your sentence could mean one thing or the exact opposite.  Good to have this change!

**Pull request merged**
