### PR TITLE
[WIP] Add throw error on failed contract creation

### LINKED ISSUE #9822: trace_filter does not return failed contract creation
- **Parity Ethereum version**: Parity-Ethereum/v2.0.8-stable-ef8f95e-20181015/x86_64-linux-gnu/rustc1.29.0
- **Operating system**: Linux
- **Installation**: Docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

`debug_trace` API for block 2,878,467 is missing the trace for transaction https://etherscan.io/tx/0xb8965886e04cdbf18132a722f5a556a378b9dbcab5d1fc4050e54eadc12fafbd. Is it an expected behaviour? If yes, what's the rationale for skipping such traces?

Below is the JSON API request and response for the block.

```
> curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock": "0x2BEC03", "toBlock": "0x2BEC03"}],"id":1}'

{
    "jsonrpc": "2.0",
    "result": [
        {
            "action": {
                "callType": "call",
                "from": "0xcaa216e03ee4932941ef0729f250e297fd5655ad",
                "gas": "0xb9d8",
                "input": "0xe637a44b000000000000000000000000000000000000000000000000000529f0a21a905f00000000000000000000000000000000000000000000000000050498d760af01",
                "to": "0xfdc77b9cb732eb8c896b152e28294521f5f62e67",
                "value": "0x0"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x5f74",
                "output": "0x"
            },
            "subtraces": 1,
            "traceAddress": [],
            "transactionHash": "0x03c0d74b32caac835805eb8eb4b174685fd72379c981369672dfee925aa720d9",
            "transactionPosition": 0,
            "type": "call"
        },
        {
            "action": {
                "callType": "callcode",
                "from": "0xfdc77b9cb732eb8c896b152e28294521f5f62e67",
                "gas": "0xae05",
                "input": "0x5035db4a0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000caa216e03ee4932941ef0729f250e297fd5655ad",
                "to": "0xfdc77b9cb732eb8c896b152e28294521f5f62e67",
                "value": "0x0"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x255",
                "output": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "subtraces": 0,
            "traceAddress": [
                0
            ],
            "transactionHash": "0x03c0d74b32caac835805eb8eb4b174685fd72379c981369672dfee925aa720d9",
            "transactionPosition": 0,
            "type": "call"
        },
        {
            "action": {
                "callType": "call",
                "from": "0x91337a300e0361bddb2e377dd4e88ccb7796663d",
                "gas": "0x10d88",
                "input": "0x",
                "to": "0x8f6e97be83af27a8ceb0b795ec6c86962c2135f6",
                "value": "0x164a5305742c38000"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x0",
                "output": "0x"
            },
            "subtraces": 0,
            "traceAddress": [],
            "transactionHash": "0x5151ddfa2cc70ddcdfb84c44dd61ed1a49c185f68e0f7ad2c15bfc4b32aff755",
            "transactionPosition": 1,
            "type": "call"
        },
        {
            "action": {
                "callType": "call",
                "from": "0xc68c06c5ee03b0d5b3b6e830b9c471571eeb8923",
                "gas": "0x10d38",
                "input": "0x0000000000000000000000000000000000000000",
                "to": "0xf90c9ac616ecfefb3860aaa5bc33caf9bc606441",
                "value": "0x380afb26cf85000"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x0",
                "output": "0x"
            },
            "subtraces": 0,
            "traceAddress": [],
            "transactionHash": "0x58e048c45856325f5ae171458b1f7a80db4b80e626407d265078c9a8960e88e3",
            "transactionPosition": 2,
            "type": "call"
        },
        {
            "action": {
                "callType": "call",
                "from": "0x11af339e6b44a1e36ebdfaa08cce5a4f16df5b0f",
                "gas": "0x10d88",
                "input": "0x",
                "to": "0xdfad8c8a6172d33b95038ec5bb067239b71f70d0",
                "value": "0x1bc09ddb5ad7f100"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x0",
                "output": "0x"
            },
            "subtraces": 0,
            "traceAddress": [],
            "transactionHash": "0x84c232c5111aaee45a0eb374d224e102bc05149dde75f29e32b428ce96c5ddbf",
            "transactionPosition": 3,
            "type": "call"
        },
        {
            "action": {
                "callType": "call",
                "from": "0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01",
                "gas": "0x4650",
                "input": "0x",
                "to": "0x82d6ab6c1d6532640d1a2cef44a7c43a66bf748c",
                "value": "0x44b1eec6162f0000"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x0",
                "output": "0x"
            },
            "subtraces": 0,
            "traceAddress": [],
            "transactionHash": "0x895a19c1058b20f07756aab6c9660ab669588ae19bd8c5843d201369b067b1ab",
            "transactionPosition": 4,
            "type": "call"
        },
        {
            "action": {
                "callType": "call",
                "from": "0x6000a0d1503631443e7833de6ed46f91d7787219",
                "gas": "0x10d88",
                "input": "0x",
                "to": "0xaf139302bc27c1ca18320d3fce01b90a74dc879b",
                "value": "0x4563918244f40000"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x0",
                "output": "0x"
            },
            "subtraces": 0,
            "traceAddress": [],
            "transactionHash": "0xecdb5c9f49351eee67347bef9d451fa7f793d575dc7bb769665acb01c5962f34",
            "transactionPosition": 6,
            "type": "call"
        },
        {
            "action": {
                "callType": "call",
                "from": "0x1e9939daaad6924ad004c2560e90804164900341",
                "gas": "0x4650",
                "input": "0x",
                "to": "0xa1af766e540b28dc551fd02d372549d55b087251",
                "value": "0x45cd921d348be3d0"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": {
                "gasUsed": "0x799",
                "output": "0x"
            },
            "subtraces": 0,
            "traceAddress": [],
            "transactionHash": "0xf52aa5d07bafcb704ba0804d2989f317c5698a0cd70064baf65ed440d06d6006",
            "transactionPosition": 7,
            "type": "call"
        },
        {
            "action": {
                "author": "0x1a060b0604883a99809eb3f798df71bef6c358f1",
                "rewardType": "block",
                "value": "0x4563918244f40000"
            },
            "blockHash": "0x667bcaac622ef255cd664fd6afc69fb86bea698de72770ea86bd71fed691a761",
            "blockNumber": 2878467,
            "result": null,
            "subtraces": 0,
            "traceAddress": [],
            "transactionHash": null,
            "transactionPosition": null,
            "type": "reward"
        }
    ],
    "id": 83
}
```

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #9822

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
clabot:check

**Comment by Tbaut** [comment]
Is this still in progress?

**Comment by 5chdn** [comment]
needs CLA signoff

**Comment by aashutoshrathi** [comment]
clabot:check

**Pull request closed without merging**
