### PR TITLE
[stable] Backport constantinople changes

### PR DESCRIPTION
**Pull request by andresilva**
## EIPs & KIPs

- [x] EIP 145 - Bitwise shifting instructions in EVM
- ~EIP 145: Bitwise shifting instructions in EVM #8451~ (already in stable)
- [x] EIP 1014 - Skinny CREATE2
- Comply EIP-86 with the new definition #9140 (637883f52b249be8284d77ac7a76968ebff4aefa)
- Add EIP-1014 transition config flag #9268 (caca3a8048e61178d86a6c455e6193e3906abafc)
- Fix a panic on create2 new opcode #9522 (65bf1086a2edc9339ab988a22754c9fea54e59a8)
- Don't hash the init_code of CREATE. #9688 (4186467129c55fcf6e6690addc529252851b9e56)
- Implement CREATE2 gas changes and fix some potential overflowing #9694 (c8ae675b95590f9353373bc48040e67b6cad7795)
- [x] EIP 1052 - EXTCODEHASH Opcode
- Implement EIP-1052 (EXTCODEHASH) and fix several issues in state account cache #9234 (29baccd857fea3d2d3298528cb3c3327b0b5af22)
- [x] EIP 1234 - Delay diff bomb
- ~Generalized blockReward and difficultyBombDelays config #9480~ (would be a breaking change to the json spec format)
- ethash: implement EIP-1234 #9187
- [x] EIP 1283 - Net gas metering for SSTORE
- EIP 1283: Net gas metering for SSTORE without dirty maps #9319 (915c36605638876629f93725887ce5d655bc0376)
- [x]  KIP 4 - "create2" Host Function for pWASM
- Implement KIP4: create2 for wasm #9277 (e8b13cb77e30f60677d09b1b4eab1a4998dde28e)
- [x] KIP 6 - "gasleft" extern
- `gasleft` extern implemented for WASM runtime (kip-6) #9357 (5ed25276635f66450925cba3081028a36de5150d)

## Chain specs & tests

- [x] Hardfork the testnets #9562 (85a6dc5e8c21ce2dab2f3218b2480e251479e29c)
- [x] ethcore: delay ropsten hardfork #9704 (1036fcca36018abf4dc5c6dedc4a2aaf560e80a7)
- [x] Update state tests execution model #9440 (6e5a1c00dc5e5141f6438f68754788237f1df816)
- [x] Enable all Constantinople hard fork changes in constantinople_test.json #9505 (530aac06822932f669b09101afbcbb40561e0894)
- [x] Add constantinople conf to EvmTestClient. #9570 (692d5b4e089047b21b1fa2c9f414923099b6d373)

# Extra backports

- [x] Fix checkpointing when creating contract failed #9514 (631df0fe5665bc9e5b578825605474b913fd782e)
- [x] Add hardcoded headers #9730 (fa2f99641ff87f4786fa4fa467d7fa22e88f7d46)
- [x] gitlab ci: releasable_branches: change variables condition to schedule #9729 (be1363e943310d0ca441c4140aa355ecba3ced0f)
- [x] HF in POA Core (2018-10-22) #9724 (73db5dda8c0109bb6bc1392624875078f973be14)

### CODE REVIEW

**Comment by sorpaas** [comment]
@andresilva Please backport https://github.com/paritytech/parity-ethereum/pull/9514 as well!

**Comment by 5chdn** [comment]
You need to cherry-pick #9681 to make CI work or rebase your PR on #9648 (you could merge it into `a5-stable-207` if you like)

**Comment by andresilva** [comment]
@5chdn Thanks, backported #9681. I think it's easier to review this if all constantinople changes are bundled in a single PR. We can rebase this over #9648 afterwards before merging.

**Comment by 5chdn** [comment]
what happened here?

**Comment by 5chdn** [comment]
Can you sneak in #9730 #9729 if you rebase anyways?

**Comment by ddorgan** [comment]
@5chdn should I force the gitlab-test-linux check into passing here? I guess it won't run gitlab-test-linux ... the .gitlab-ci.yml in that branch is 21 days old...

**Comment by 5chdn** [comment]
No, thanks @ddorgan, Andre will rebase in a second.

**Pull request merged**
