### PR TITLE
Treat blocks, that already downloaded, as synced

### PR DESCRIPTION
**Pull request by grbIzl**
This PR aims to fix the following scenario in the block sync:

1. Node downloads the next block number N and starts importing it. Due to block's complexity or some configuration issues block's import takes more time (I've seen this issue, when import took 5-10 seconds).
2. Meanwhile the next sync round has begun and Parity tries to sync block N once more time, obviously import of this block has no success with error AlreadyQueued. As a result the sync round has completed with 0 blocks synced
3. As no new blocks were synced during sync round Parity starts descending in block number, treating this situation as error during blocks download: https://github.com/paritytech/parity-ethereum/blob/master/ethcore/sync/src/block_sync.rs#L429 and repeats sync for (already downloaded) blocks
4. Attempt to sync block number N-1 returns the same error and causes attempt to download block N-2 and so on
5. This downfall only finishes, when (if) block number N is imported and Parity catches up the current best block
6. As a result huge DDOS of GetBlock requests outcomes from the node. This also can affect current block's verification and exacerbates the issue.

Suggested solution:
Treat downloaded blocks on step 2 and further, that exist already in the chain or in the queue, as actually  synced on this round and (as result) do not start error handling procedure with blocks descending. 

Comments: 

- Relates to #10724. 
- Also such DDOS can cause the hanging of other node (see #10821 ), that replies to these massive GetBlocks requests.
- This issue has similarities to the described in https://github.com/paritytech/parity-ethereum/pull/9531 but has different scenario and root causes are not connected.

### CODE REVIEW

**Comment by grbIzl** [comment]
I put this PR to onice in order to perform more testing. Please do not merge it before it's done.

**Comment by dvdplm** [comment]
@tomusdrw Can you take a look at this please? What are the consequences of considering blocks that are currently getting processed as imported?

**Comment by grbIzl** [comment]
This change breaks fork's handling logic in block sync. More accurate approach is required

**Comment by grbIzl** [comment]
> Since we can only import one block a the time, can't we have an atomic operation that actually makes sure that we shouldn't re-try importing it, cause it's already being imported?

It already works so. Probably I was not able to emphasize this subtle difference between importing and syncing of blocks. Saying syncing, I meant downloading of block's header, body etc. Import happens for synced block and it is indeed atomic and we don't allow multiple re-imports of the block. The problem, that this PR addresses, is multiple re-sync of already synced blocks. 

>Alternatively we could return a different error code than AlraedyQueued to distinguish this situation.

I came to the nearly the same solution.

**Comment by lazaridiscom** [comment]
As a general rule, Error-Codes should reflect reality. Thus, changing "AlreadyQueued" to the real error-code like e.g. "ImportOngoing", is the first step to take. The act on this error-code, in an non-breaking manner.

Changing the logic, place atomic operations etc. should be avoided, because this can introduce unexpected behavior.

**Comment by lazaridiscom** [comment]
> (I've seen this issue, when import took 5-10 seconds

possibly related to #10085

**Comment by grbIzl** [comment]
PR is verified. Closing it in favor of the newly created #11264 with clear history.

**Pull request closed without merging**
