### PR TITLE
Allow sealing when bugfix hardforks activate later than block 0

### PR DESCRIPTION
**Pull request by jwasinger**
Some networks (like Rinkeby) rely on this.

### CODE REVIEW

**Comment by jwasinger** [comment]
I'd also suggest making the message a trace instead of warning.  That way, it won't clog the output unless tracing for the miner is turned on.

**Comment by sorpaas** [comment]
Or at least, @jwasinger, if you really need this, I would advise to do it like this:

* Add a new command line flag, like `--allow-insecure-first-block-sealing`.
* Keep current behavior, and only skip the check if the flag is on.

In this way, we make sure the configurators know what they're doing before proceeding. There're only three bugfix hard forks EIP155, `validate_receipts`, `validate_chain_id`. All of which if a network disables it, it can be really insecure.

**Comment by sorpaas** [comment]
This if branch can only be triggered on Rinkeby if it fails to connect to any other peers (and tries to seal again another block 1). In all other cases, it's either a bug in the client or the config file.

The check won't affect any established networks (Foundation, Rinkeby, etc), but will only warn and stop sealing block 1 for a new network.

**Comment by 5chdn** [comment]
@jwasinger does this do anything beyond printing the warning?

**Comment by jwasinger** [comment]
@sorpaas @5chdn I think I was mistaken and that my client was actually just taking an unusually long amount of time to find an connect to peers...

One side effect of not including this PR is that users will be able to sync to Rinkeby, but if they try and spin up a private network with the same configuration, it will fail.

**Pull request closed without merging**
