### PR TITLE
Only check warp syncing for eth_getWorks

### PR DESCRIPTION
**Pull request by sorpaas**

### CODE REVIEW

**Comment by 5chdn** [comment]
That only affects master 2.1.0+, does it?

**Comment by sorpaas** [comment]
It affects anything after #9210. So I think that means beta and stable.

**Comment by fckt** [comment]
I'd like to add my review, but I need to understand some context first.. Why we don't need to check for `is_major_importing` but check only for `is_warp_syncing` here?

**Comment by sorpaas** [comment]
@fckt the issue is that using `is_major_importing` may break this RPC call for some miners. A peer may cause the client to occasionally switch to `SyncState::Blocks` (considered syncing by `is_major_importing`), while the client is really close to chain head.

**Comment by sorpaas** [comment]
I'm going to add the blocker tag for this PR, because if this is indeed an issue, then pow for some chains may have been broken.

**Pull request merged**
