### PR TITLE
WIP: Add Gangnam testnet support

### PR DESCRIPTION
**Pull request by naikmyeong**
_**Please do not merge or close this PR yet, this is for WIP only!!**_

See also: https://github.com/ethereum/go-ethereum/pull/18245

### What is Gangnam Testnet?
Gangnam testnet is a proof of work testnet to test **alternative proof-of-work algorithms** like [progpow](https://eips.ethereum.org/EIPS/eip-1057) or [tethashv1](https://github.com/ethereum/EIPs/blob/7336cceac6c997252299a463ffe896a3414c479b/EIPS/eip-1485.md), [eip-1355](https://eips.ethereum.org/EIPS/eip-1355), it is supposed to provide a public testnet environment to test pow softwares like nodes, miners, or pool implementations.

### Proposed specification for Gangnam Testnet
+ Spec for Geth: goldenethereum/golden-ethereum@ee97595

+ Spec for Parity-Ethereum: goldenethereum/parity-ethereum@9b79304

### List any resources for gangnam testnet here
+ Discord community: http://discord.gg/HvpucP7

+ Block Explorer and Pool WIP

### CODE REVIEW

**Comment by 5chdn** [comment]
what peter said

**Comment by 5chdn** [comment]
If you want to contribute, you could remove eos-classic, eth-social, and easthub.

**Comment by naikmyeong** [comment]
@5chdn Nah. I don't own them 😂

**Comment by naikmyeong** [comment]
This PR is for common study of progpow, as I've already said.

**Pull request closed without merging**
