### PR TITLE
Hardfork the testnets

### PR DESCRIPTION
**Pull request by 5chdn**
- propose constantinople hardfork at `4_200_000` on ropsten
    - eip 145, 1014, 1052, 1234, 1283
- propose constantinople-like harfork at `9_200_000` on kovan
    - eip 145, 1014, 1052, 1283
    - kip 4, 6

both hardforks will be around mid october. ~~putting it _on ice_ for discussion, waiting for the core developers to finalize the block number.~~ done.

~~main question for me now, is there anything missing for the fork in the spec? @sorpaas~~ looks good?

~~also, do we want to activate dynamic validators finally? @tomusdrw @andresilva~~ too short call.

~~and [kip-4](https://github.com/kovan-testnet/KIPs/blob/33a116649116ddad656302311080438264bb2dba/KIPs/kip-4.md), [kip-6](https://github.com/kovan-testnet/KIPs/blob/9c2e1387cd69e281c723d01084655da77cb7fa68/kip-6.md)? cc @NikVolf~~ done

### CODE REVIEW

**Comment by NikVolf** [comment]
Yeah, I see no problem introducing kip-6 and kip-4 in the same hardfork

**Comment by andresilva** [comment]
@5chdn I'm ok with migrating to dynamic validator set. I can prepare this and we can test the HF next week and then decide whether we include it or not.

**Comment by 5chdn** [comment]
Ok, cool!

**Comment by eosclassicteam** [comment]
@5chdn 4.2M is official from last dev call https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2047.md#constantinople, we should rebase this PR and change the block num to 4.2M for Ropsten.

And we need new release before Oct. 9, we will update our bootnode if new version released :smile:

**Pull request merged**
