### PR TITLE
Update json tests

### PR DESCRIPTION
**Pull request by cheme**
This is ongoing process (currently just moved the submodule reference).
cc @adilimroz

### CODE REVIEW

**Comment by soc1c** [comment]
The reason we did not update them, is because the testing team didn't tag a release yet.

Can we figure out if there is any plan to tag a release upstream? (We recently decided to only use specific versions of the tests and not randomly update the develop branch)

**Comment by cheme** [comment]
Sure, we are only preparing the PR yet (there is still some missing/new test I think @adilimroz is looking into it).

**Comment by ordian** [comment]
@cheme @adilimroz any updates on this?

**Comment by cheme** [comment]
I just checked, no new tag on eth tests repo.

**Comment by debris** [comment]
closing in favor of #10923 . Missing blockchain tests shall be also added to that pr

**Pull request closed without merging**
