### PR TITLE
allow rust-nightly builds fail in nightly builds

### PR DESCRIPTION
**Pull request by gabreal**
https://doc.rust-lang.org/cargo/guide/continuous-integration.html#gitlab-ci

allow rust-nightly builds to fail

https://gitlab.parity.io/parity/parity-ethereum/pipelines/26136

### CODE REVIEW

**Comment by ordian** [comment]
I filed an issue for rust https://github.com/rust-lang/rust/issues/56069.

**Comment by ordian** [comment]
@gabreal Since test-nightly is in optional stage, is it technically allowed to fail already?

**Comment by gabreal** [comment]
The whole pipeline is marked as failed regardless of a stage being called optional - that's just a name.

**Comment by gabreal** [comment]
but even with allow_failure the job will still be run, its result just won't be counted to the final result. I think it's more about notifications here.

**Pull request merged**
