### PR TITLE
Add EOS Classic network support

### PR DESCRIPTION
**Pull request by eosclassicteam**
EOS Classic is a combination of ETH & EOS protocol network

We would like to request adding EOS Classic Mainnet support on parity-ethereum client

### Coin info

+ Homepage: https://eos-classic.io
+ Explorer: https://explorer.eos-classic.io , https://eosctracker.com ( Now running with parity node )
+ Netstats: https://stats.eos-classic.io
+ Twitter: https://twitter.com/eosclassic.io
+ Chainid and networkid is "0x14"
+ Currently supported by MyEtherWallet, MyCrypto, and Trezor wallet

### PR changes

+ Added EOSC Bootnodes from go-eosclassic
+ Added NewEOSC Hardfork logic
+ Tested with rust-eosclassic
+ Apply EOSC-1017 Reward

cc @5chdn @sorpaas @Tbaut @andresilva

### CODE REVIEW

**Comment by eosclassicteam** [comment]
@sorpaas Thanks for your comment, may I ask if reward contract is compatible with geth? ( Or should I deploy it somewhere? )

**Comment by sorpaas** [comment]
It's geth-compatible. You won't need to deploy the reward contract anywhere. Simply calculate the correct block rewards and embed the resulting EVM contract code to `blockRewardContractCode` param.

**Comment by 5chdn** [comment]
Please reopen once ready.

**Comment by andresilva** [comment]
You can find an example of using the block reward contract in #9605 to implement the Musicoin block reward logic, there's also a gist there with instructions on how to build the contract.

**Pull request closed without merging**
