### PR TITLE
Add Foundation Bootnodes

### PR DESCRIPTION
**Pull request by eosclassicteam**
bootnodes

Running on AWS by @eosclassicteam with ❤️

### CODE REVIEW

**Comment by ddorgan** [comment]
[clabot: check]

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by sorpaas** [comment]
This needs rebase on master.

**Comment by eosclassicteam** [comment]
@5chdn @sorpaas Rebased with master branch thanks 👍

**Pull request merged**
