### PR TITLE
Docker alpine: use multi-stage concept

### PR DESCRIPTION
**Pull request by fanatid**
This brings multi-stage concept and nonroot user.
Current image size is 1.42GB, with this Pull Request 58.2MB (20MB compressed on docker hub)

### CODE REVIEW

**Comment by fanatid** [comment]
[clabot:check]

**Comment by sorpaas** [comment]
@fanatid Merge #9270 would fix this CI build.

**Comment by fanatid** [comment]
@sorpaas thanks, rebased

**Comment by JohnnySheffield** [comment]
Do we care about supporting lower versions of Docker? For multistage builds one needs Docker 17.05.

**Comment by fanatid** [comment]
Yes, multistage require Docker >= 17.05 :(
I can rewrite it without multistage without significant changes of image size, if this required.

**Comment by JohnnySheffield** [comment]
I was kinda 50:50 with #9231 but then decided to go with supporting <17.05 I'm also not sure about different platform support. For instance, i think docker rpm package for RHEL is v1.13

I'm ready to rework  #9231 to go with multistage builds if needed, but i think this is more of a question for Parity team what their plans are

**Pull request merged**
