### PR TITLE
Update ProgPoW to 0.9.3

### PR DESCRIPTION
**Pull request by ethcoreorg**
0.9.2 version is deprecated due to efficiency

See 0.9.3 specification on https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1057.md#specification

### CODE REVIEW

**Comment by andresilva** [comment]
@ethcoreorg how did you update the values for the test vectors? Did you confirm we're getting the same results as other implementations?

**Comment by ethcoreorg** [comment]
@andresilva Why not sure https://github.com/ethereum/EIPs/blob/master/assets/eip-1057/test-vectors-0.9.3.json, it has already been published on EIPs

**Comment by ethcoreorg** [comment]
I've also confirmed that the test vector works for go-ethereum implementation also https://github.com/holiman/go-ethereum/pull/4

**Comment by andresilva** [comment]
@ethcoreorg I saw the EIP link you posted and checked the changes in constants but didn't notice the test vectors. Thanks! :)

**Pull request merged**
