### PR TITLE
Rip out the C and Java bindings

### PR DESCRIPTION
**Pull request by DemiMarie-parity**
I am not aware of them having any users, and they required a nontrivial amount of maintainance.  They also do not have any useful functionality that cannot be obtained by making JSON-RPC calls to a separate Parity Ethereum process over IPC.

✄ -----------------------------------------------------------------------------

### CODE REVIEW

**Comment by ordian** [comment]
AFAIR they were supposed to be used in the light client on Android, cc @amaurymartiny @tomaka

**Comment by tomaka** [comment]
Yeah, they were supposed to be used in environments where you'd use parity-ethereum as a library.

cc'ing @folsen

**Comment by TriplEight** [comment]
Great job here! 
Wanted to ask didn't you forget to remove android, which is `parity-clib` ?

**Comment by tomaka** [comment]
Wait, did we actually want to do that? I thought these bindings were in use.

**Comment by dvdplm** [comment]
> Wanted to ask didn't you forget to remove android, which is `parity-clib` ?

@DemiMarie-parity can you answer this please, I'm curious too.

**Comment by niklasad1** [comment]
> Wanted to ask didn't you forget to remove android, which is parity-clib ?

It is fixed

**Comment by DemiMarie-parity** [comment]
> Wait, did we actually want to do that? I thought these bindings were in use.
> 
> > They also do not have any useful functionality that cannot be obtained by making JSON-RPC calls to a separate Parity Ethereum process over IPC.
> 
> Except on platforms such as Android that don't have IPC.

Android *does* have IPC.  It supports AF_UNIX just fine last I checked.  If it doesn’t, that is news to me.  You can run a full \*nix shell on Android, and there are several apps that do.  It even comes with a full set of command line utilities as part of the OS.

*iOS* does not support IPC, but Parity Ethereum is not useful on that platform because of licensing.

**Pull request merged**
