### PR TITLE
Updated Bn128PairingImpl to use optimized batch pairing 

### PR DESCRIPTION
**Pull request by seunlanlege**
original PR #10624

### CODE REVIEW

**Comment by andresilva** [comment]
What's different from the original PR? Also I think we have benchmarks for this, can we run them before and after the change to check the improvement?

**Comment by seunlanlege** [comment]
@andresilva this PR has been rebased with the master branch, 

benchmarks for this branch 
https://gist.github.com/zac-williamson/71b67b994c8b7be4de263fe31dc2eb21

**Comment by andresilva** [comment]
The diff between this PR and #10624 is the same. Also do I understand correctly that all bn128 benchmarks actually got slower with this change?

**Comment by seunlanlege** [comment]
> This provides an approximate 2x increase in the speed of the algorithm, when multiple pairings are being computed at once.

from the original author.

**Comment by dvdplm** [comment]
@andre yes, it’s the same PR but as the original author was busy we’re taking over. Mainly to double check the perf improvement claim.

**Comment by ordian** [comment]
I've got the following results: https://gist.github.com/ordian/eeb56b65c44580aa59f60013bea2322b

**Comment by andresilva** [comment]
@ordian Thanks for re-running the benchmarks. :+1:

**Pull request merged**
