### PR TITLE
fix windows compilation, replaces #9561

### PR DESCRIPTION
**Pull request by debris**
replaces #9561

### CODE REVIEW

**Comment by ordian** [comment]
what about #9604?

**Comment by debris** [comment]
oh, I haven't noticed it... but it contains a lot of unrelated changes. I would prefer to merge this one instead (as this x-compiles fine on my machine) rather than reverse a lot of unnecessary libraries

**Comment by ordian** [comment]
> as this x-compiles fine on my machine

doesn't seem to compile here

**Comment by debris** [comment]
I also had to downgrade `tokio-named-pipes` ...

**Comment by debris** [comment]
@paritytech/ci `retry` for `gitlab-test-windows-rust-stable ` seems to fail

**Comment by General-Beck** [comment]
test failed https://gitlab.parity.io/parity/parity-ethereum/-/jobs/100290

**Comment by debris** [comment]
@andresilva @tomusdrw can you review and merge?

**Comment by 5chdn** [comment]
Tests fail

**Comment by debris** [comment]
@5chdn failing test is unrelated and I believe we should address is separately :)

**Pull request merged**
