### PR TITLE
WIP: New docker image name

### PR DESCRIPTION
**Pull request by TriplEight**
New registry name is not there yet, waiting for it.
- now we publish `parity/parity` image, which inherits from `parity/ethereum` and has a deprecation notice

### CODE REVIEW

**Comment by ddorgan** [comment]
[clabot:check]

**Comment by debris** [comment]
what is the status of this pr?

**Comment by TriplEight** [comment]
stale, yes. Will return to it soon-ish.

**Comment by dvdplm** [comment]
@TriplEight any update on this?

**Comment by TriplEight** [comment]
closing for some time, it's not decided yet.

**Pull request closed without merging**
