### PR TITLE
Add POA Networks: Core and Sokol

### PR DESCRIPTION
**Pull request by 5chdn**
- Add POA Network Core mainnet chain spec `--chain poanet`
- Add POA Network Sokol testnet chain spec `--chain sokol`
- Cleaned up a bit the code and docs:
    - rearranged networks by public / testnet and (my subject perception of) size
    - changed docs to not list all networks everywhere, this is about to blow up
- Allow users to run `--chain ethereum` or `--chain byzantium` for foundation network
- Amended tests `test_spec_type_parsing` and `test_spec_type_display`
- Allow Sokol users to use the insecure 0x00a329 account ...

### CODE REVIEW

**Comment by 5chdn** [comment]
paging @rstormsf @phahulin if you want to test this.

**Comment by phahulin** [comment]
Could you also update network names as displayed in logs please

to "POA Core"
```
2018-08-24 23:18:34  Configured for POA Network using AuthorityRound engine
```

to "POA Sokol"
```
2018-08-24 23:44:01  Configured for Sokol using AuthorityRound engine
```

**Comment by 5chdn** [comment]
I'm a bit conflicted because in my head POA is not a brand but a consensus mechanism. Calling a network "POA Core" sounds confusing, while "POA Network" is clearly the name of your product. I'm fine with "POA Sokol" though if you insist.

**Comment by eosclassicteam** [comment]
POA at last 😄

**Comment by rstormsf** [comment]
Looks good to me. 
👍 I was just thinking about it today.

**Comment by phahulin** [comment]
@5chdn yes please, let's have `POA Sokol`

**Comment by 5chdn** [comment]
Done.

**Comment by 5chdn** [comment]
> Will rebase the callisto one after this PR is merged

yes this makes actually sense.

**Pull request merged**
