### PR TITLE
Comply EIP210 with the current spec

### PR DESCRIPTION
**Pull request by sorpaas**
Change BLOCKHASH contract code to be the current one. It looks like the rest hasn't been changed.

### CODE REVIEW

**Comment by sorpaas** [comment]
Putting this on ice. The new spec looks like breaking some of our current assumptions. https://github.com/ethereum/EIPs/pull/210#issuecomment-410148601

**Comment by sorpaas** [comment]
Waiting on https://github.com/ethereum/EIPs/pull/1094

**Comment by 5chdn** [comment]
How to proceed with that now? Is 210 going anywhere anytime soon?

**Comment by sorpaas** [comment]
Still waiting on https://github.com/ethereum/EIPs/pull/1094 actually. After that spec is done, we can modify our code to comply, although EIP-210 itself is not used anywhere right now.

**Comment by 5chdn** [comment]
Please reopen once the spec is complete

**Comment by zmitton** [comment]
@5chdn it seems #1094 has been merged. Does that me this should be re-opened?

**Pull request closed without merging**
