### PR TITLE
v2.5.10 stable

### PR DESCRIPTION
**Pull request by soc1c**
- [x]  ropsten #6631425 foundation #8798209 (#11201) 
- [x] [stable] builtin, istanbul and mordor testnet backports (#11234) 
    - ethcore-builtin (#10850)
    -  [builtin]: support `multiple prices and activations` in chain spec (#11039)
    - [chain specs]: activate `Istanbul` on mainnet (#11228)
    - ethcore/res: add mordor testnet configuration (#11200)
- [x] Update list of bootnodes for xDai chain (#11236)
- [x] ethcore: remove `test-helper feat` from build (#11047) 
- [x] Secret store: fix Instant::now() related race in net_keep_alive (#11155) (#11159)
- [x] [stable]: backport #10691 and #10683 (#11143)
    - Fix compiler warning (that will become an error) (#10683)
    - Refactor Clique stepping (#10691)
- [x] Add Constantinople eips to the dev (instant_seal) config (#10809)
- [x] Add cargo-remote dir to .gitignore (?)
- [ ] ~~Snapshot restoration overhaul (#11219)~~
- [x] Insert explicit warning into the panic hook (#11225)
- [x] Fix docker centos build (#11226)
- [x] Update MIX bootnodes. (#11203)
- [x] Use provided usd-per-eth value if an endpoint is specified (#11209)
- [x] Add new line after writing block to hex file. (#10984)
- [ ] ~~Pause pruning while snapshotting (#11178)~~
- [x] Type annotation for next_key() matching of json filter options (#11192) (but no `FilterOption` in 2.5 so…)
- [x] Upgrade jsonrpc to latest (#11206)
- [ ] [CI] check evmbin build (#11096)
- [x] Correct EIP-712 encoding (#11092)
- [x] [client]: Fix for incorrectly dropped consensus messages (#11086)
- [ ] ~~Update JSON tests to d4f86ecf4aa7c (#11054)~~
- [ ] ~~Update hardcoded headers (foundation, classic, kovan,  xdai, ewc, ...) (#11053)~~
- [x] Fix block detail updating (#11015)
- [x] Switching sccache from local to Redis (#10971)
- [x] Made ecrecover implementation trait public (#11188)
- [x] [dependencies]: jsonrpc `14.0.1` (#11183)
- [x] [receipt]: add `sender` & `receiver` to `RichReceipts` (#11179)
- [x] [ethcore/builtin]: do not panic in blake2pricer on short input (#11180)
- [x] util Host: fix a double Read Lock bug in fn Host::session_readable() (#11175)
- [x] ethcore client: fix a double Read Lock bug in fn Client::logs() (#11172)
- [x] Change how RPCs eth_call and eth_estimateGas handle "Pending" (#11127)
- [x] Cleanup stratum a bit (#11161)
- [x] Upgrade to jsonrpc v14 (#11151)
- [x] SecretStore: expose restore_key_public in HTTP API (#10241)
- [x] Filter out some bad ropsten warp snapshots (#11247)
- [x] Make InstantSeal instant again (#11186)

### CODE REVIEW

**Comment by soc1c** [comment]
Waiting for #11212

**Comment by soc1c** [comment]
All these years and the CI doesn't do its job

**Comment by s3krit** [comment]
Our intent is to do one final v2.5 release for Istanbul. There are a few more PRs that need backporting too.

**Comment by soc1c** [comment]
Yeah just noticed. When was the last stable release?


TODO:
- [ ] Snapshot restoration overhaul (#11219)
- [ ] Insert explicit warning into the panic hook (#11225)
- [ ] Fix docker centos build (#11226)
- [ ] Update MIX bootnodes. (#11203)
- [ ] Use provided usd-per-eth value if an endpoint is specified (#11209)
- [ ] Add new line after writing block to hex file. (#10984)
- [ ] Pause pruning while snapshotting (#11178)
- [ ] Type annotation for next_key() matching of json filter options (#11192)
- [ ] Made ecrecover implementation trait public (#11188)
- [ ] [dependencies]: jsonrpc `14.0.1` (#11183)
- [ ] [receipt]: add `sender` & `receiver` to `RichReceipts` (#11179)
- [ ] [ethcore/builtin]: do not panic in blake2pricer on short input (#11180)
- [ ] util Host: fix a double Read Lock bug in fn Host::session_readable() (#11175)
- [ ] ethcore client: fix a double Read Lock bug in fn Client::logs() (#11172)
- [ ] Change how RPCs eth_call and eth_estimateGas handle "Pending" (#11127)
- [ ] Cleanup stratum a bit (#11161)
- [ ] Upgrade to jsonrpc v14 (#11151)
- [ ] SecretStore: expose restore_key_public in HTTP API (#10241)

**Comment by dvdplm** [comment]
Ok, I think this is done. I synced goerli from genesis but it'd be great to do some more testing.
/cc @adilimroz

**Pull request merged**
