### PR TITLE
fix(parity-clib-example): remove websocket

### PR DESCRIPTION
**Pull request by niklasad1**
I suspect there is something wrong with the `WebSocket subscription` in the light client so let's remove it for now in order not to deny well-formed PRs!

/cc @tomusdrw @ngotchac

### CODE REVIEW

**Comment by tomusdrw** [comment]
@niklasad1 you can subscribe to `eth_subscribe(newHeads)` @mattrutherford recently changed this so it's emitted even when syncing (see #9987)

**Comment by niklasad1** [comment]
Thanks @tomusdrw 

I found out this yesterday too when I tested it locally too.

> I was wrong the websocket works without being fully synced tested locally now but it seems to some problem with ChainNotify in the light-client sometimes it works and sometimes not. I think I had some problem with it before but has worked locally for me for a while now

Thus, I need to debug if there is something weird with the `ChainNotify` for the light client (I have not confirmed it yet) and should probably be disabled for the CI to prevent other PRs to fail randomly.

**Comment by tomaka** [comment]
I can also be the C++ example or C bindings that have an undefined behaviour, as opposed to the Rust code having a bug.

**Comment by niklasad1** [comment]
Closing until the error-cause is confirmed which could be UB as @tomaka stated!

**Pull request closed without merging**
