### PR TITLE
remove ssl from dockerfiles

### LINKED ISSUE #8880: Cleanup dependencies from Dockerfiles
Remove `libssl`. Ref #8878.

### PR DESCRIPTION
**Pull request by debris**
closes #8880

@paritytech/ci can you check if modified dockerfiles build fine?

### CODE REVIEW

**Comment by ddorgan** [comment]
@debris somewhat unrelated but it won't build now due to it trying to cd into the parity directory instead of parity-ethereum (or checkout the directory as parity instead of parity-ethereum)...

```
  stable installed - rustc 1.27.2 (58cc626de 2018-07-18)


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
Cloning into 'parity-ethereum'...
/bin/sh: 1: cd: can't cd to parity

```

**Comment by debris** [comment]
@ddorgan I see, I will fix it. btw. what script produced the output that you just pasted?

**Comment by andresilva** [comment]
@debris https://github.com/paritytech/parity-ethereum/pull/9195/files#diff-c76ef29aae3295079b52e4f353ad1d7cL39

**Comment by debris** [comment]
god, we are we pulling ethereum using git? docker should use local version of the repo

**Comment by debris** [comment]
I'll fix it

**Comment by debris** [comment]
oh, I see that it contains a `BUILD_TAG` flag... but it's a stupid solution, cause different branches of parity may have different requirements

**Comment by andresilva** [comment]
@debris Are you going to push those fixes to this branch or should we merge this PR? We can also remove ssl requirements from snapcraft definition (https://github.com/paritytech/parity-ethereum/blob/master/snap/snapcraft.yaml#L36).

**Comment by debris** [comment]
@andresilva no, let's make a separate pr for them

**Pull request merged**
