### PR TITLE
Support MIX.

### PR DESCRIPTION
**Pull request by ethernomad**
MIX is an Ethereum-based blockchain created specifically as a trust-less publishing platform.

https://www.mix-blockchain.org/

MIX can be synchronised with Parity or Geth with a config file, or with Multi-geth without a config file: https://github.com/ethoxy/multi-geth/commit/0fa476226c1b7e88de7038c2068e7ad390314e78

I would like Parity to have built-in support for MIX also.

It will soon be possible to store MIX on Ledger wallets: https://github.com/kvhnuke/etherwallet/pull/2096/commits/ea8c1f0e6027588a18634a1e9c1523b8ea379620

### CODE REVIEW

**Comment by ethernomad** [comment]
[clabot:check]

**Comment by 5chdn** [comment]
Why is there a difference between:

- https://blocks.mix-blockchain.org/
- https://stats.mix-blockchain.org/

**Comment by ethernomad** [comment]
Which difference are you referring to?

**Comment by 5chdn** [comment]
Block explorer shows 6.5 million blocks, network status 2.9 million

**Comment by ethernomad** [comment]
> Block explorer shows 6.5 million blocks, network status 2.9 million

You have metamask enabled.

**Pull request merged**
