### PR TITLE
Add Callisto Mainnet and Testnet

### PR DESCRIPTION
**Pull request by yograterol**
Hi, I'm Callisto co-founder, in this PR I added the needed code to run Callisto mainnet and Testnet (Called Galilei) on Parity.

## Callisto info

Website: https://callisto.network
Whitepaper: https://whitepaper.callisto.network

### Chain

Testnet -> `galilei`
Mainnet -> `callisto`

The code has little changes to run Callisto with Treasury and Stake funds.

### CODE REVIEW

**Comment by yograterol** [comment]
[clabot:check]

**Comment by yograterol** [comment]
@sorpaas done

**Comment by 5chdn** [comment]
Could you rebase this on current master?

56 commits and 155 files changed sounds wrong; impossible to review right now.

**Comment by 5chdn** [comment]
Maybe template it on top of #9413

**Comment by 5chdn** [comment]
Did you test it actually? I get a consensus issue.

```
2018-08-25 18:48:01  Starting Parity/v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0
2018-08-25 18:48:01  Keys path /home/user/.local/share/io.parity.ethereum/keys/Callisto
2018-08-25 18:48:01  DB path /home/user/.local/share/io.parity.ethereum/chains/Callisto/db/1b2904ad30128c93
2018-08-25 18:48:01  Path to dapps /home/user/.local/share/io.parity.ethereum/dapps
2018-08-25 18:48:01  State DB configuration: archive +Fat +Trace
2018-08-25 18:48:01  Operating mode: active
2018-08-25 18:48:01  Configured for Callisto using Ethash engine
2018-08-25 18:48:02  Public node URL: enode://ac1977d8753fc12dd801e87139c0fd56fed3bac136c8a9cafe4f82e147612f3232266e7f4c74d869722fd26ecefff42496ea7b2225d624d432c123f5f4ed44b8@192.168.2.60:30303
2018-08-25 18:48:04  Stage 5 block verification failed for #1 (2f65…85ff)
Error: Block(InvalidStateRoot(Mismatch { expected: 3c0ad8734c52ae50933b37940da4ad56e4e65e92e063729b35109c80b80f04e6, found: ad1b1dd219e2f8c47ea013e39c16b660a601b8d590ca4603145355984f4a4ad8 }))
2018-08-25 18:48:06  Syncing       #0 8227…d2c4     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0    2/256 peers   8 KiB chain 0 bytes db 0 bytes queue 324 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
```

**Comment by sorpaas** [comment]
As #9312 is merged, please rebase this on master and use `blockRewardContractCode` for custom block reward logic.

**Comment by yograterol** [comment]
@sjeohp ok, I will rebase with master.

**Comment by 5chdn** [comment]
Please let me know when you are ready.

**Pull request closed without merging**
