### PR TITLE
Extract state-db from ethcore

### PR DESCRIPTION
**Pull request by dvdplm**
Builds on https://github.com/paritytech/parity-ethereum/pull/10840 – relevant commits are the last three and especially https://github.com/paritytech/parity-ethereum/pull/10858/commits/40aef4422ebbfba4a18a97c5728efae55f4588b8

Moves ethcore/state_db to its own crate. Reduces the public API somewhat.

### CODE REVIEW

**Comment by seunlanlege** [comment]
@dvdplm please rebase, reviewing this will take a while

**Comment by dvdplm** [comment]
> @dvdplm please rebase, reviewing this will take a while

It's really only https://github.com/paritytech/parity-ethereum/commit/40aef4422ebbfba4a18a97c5728efae55f4588b8 that is relevant, but it'd be fantastic to get a review on the full https://github.com/paritytech/parity-ethereum/pull/10840 as well! :)

**Comment by ordian** [comment]
the 40aef44 lgtm, although having a circular dependency for tests is unfortunate
Will approve after #10840 is merged and this PR is rebased.

**Comment by dvdplm** [comment]
@seunlanlege @ordian ptal

**Pull request merged**
